/* Permanent public URL contract. Change internal targets, never recycle public slugs. */
(function (global) {
  'use strict';
  var routes = [
    {"route": "page/home", "type": "page", "passageId": "triage", "cardId": null, "name": "Where are you right now?"},
    {"route": "tool/before-the-next-move", "type": "tool", "passageId": "one-beat", "cardId": null, "name": "A second before the next move"},
    {"route": "page/urgent-support", "type": "page", "passageId": "crisis-now", "cardId": null, "name": "Crisis support"},
    {"route": "page/low-flat-or-shut-down", "type": "page", "passageId": "hypoarousal", "cardId": null, "name": "Low, flat, or shut down"},
    {"route": "page/grief", "type": "page", "passageId": "grief", "cardId": null, "name": "Grief"},
    {"route": "page/grief-and-death", "type": "page", "passageId": "grief-death", "cardId": null, "name": "Grief — someone who has died or is dying"},
    {"route": "page/after-a-death", "type": "page", "passageId": "grief-death-died", "cardId": null, "name": "Grief — someone who has died"},
    {"route": "page/when-someone-is-dying", "type": "page", "passageId": "grief-death-dying", "cardId": null, "name": "Grief — losing someone slowly"},
    {"route": "page/living-loss", "type": "page", "passageId": "grief-living", "cardId": null, "name": "Grief — someone still here"},
    {"route": "page/grieving-self-and-future", "type": "page", "passageId": "grief-self-future", "cardId": null, "name": "Grief — self, role, or future"},
    {"route": "page/multiple-losses", "type": "page", "passageId": "grief-multiple", "cardId": null, "name": "Grief — more than one thing"},
    {"route": "page/grief-support", "type": "page", "passageId": "grief-support", "cardId": null, "name": "Grief — things that can help"},
    {"route": "tool/sort-through-a-relationship", "type": "tool", "passageId": "relationship", "cardId": null, "name": "Sort through a relationship"},
    {"route": "page/sort-through", "type": "page", "passageId": "sort-through", "cardId": null, "name": "Sort through something"},
    {"route": "page/sort-through-reflection", "type": "page", "passageId": "sort-through-reflect", "cardId": null, "name": "Reflect on what you named"},
    {"route": "page/boundaries-and-communication", "type": "page", "passageId": "interpersonal", "cardId": null, "name": "Set a boundary or say no"},
    {"route": "page/prepare", "type": "page", "passageId": "anticipatory", "cardId": null, "name": "Preparing for something difficult"},
    {"route": "page/settle", "type": "page", "passageId": "overwhelmed", "cardId": null, "name": "Grounding through overwhelm"},
    {"route": "page/body-tools", "type": "page", "passageId": "body", "cardId": null, "name": "Body-based regulation"},
    {"route": "tool/running-on-empty", "type": "tool", "passageId": "running-on-empty", "cardId": null, "name": "Running on empty — body-needs side check"},
    {"route": "tool/name-whats-here", "type": "tool", "passageId": "emotion-labeling", "cardId": null, "name": "Emotional labeling sequence", "mode": "distress"},
    {"route": "tool/one-small-move", "type": "tool", "passageId": "small-move", "cardId": null, "name": "Note a possible next step"},
    {"route": "page/emotions", "type": "page", "passageId": "emotions", "cardId": null, "name": "Working with emotions"},
    {"route": "page/finding-direction", "type": "page", "passageId": "stuck", "cardId": null, "name": "Finding direction"},
    {"route": "page/bring-in-support", "type": "page", "passageId": "alone", "cardId": null, "name": "Bring in support"},
    {"route": "tool/support-plan", "type": "tool", "passageId": "support-plan-guided", "cardId": null, "name": "Support plan — guided"},
    {"route": "page/thought-loops", "type": "page", "passageId": "thought-spiral", "cardId": null, "name": "Breaking thought loops"},
    {"route": "tool/looping-thought", "type": "tool", "passageId": "thought-spiral-guided", "cardId": null, "name": "Guided defusion sequence"},
    {"route": "tool/reframe-inner-critic", "type": "tool", "passageId": "self-talk-guided", "cardId": null, "name": "Inner critic reframe sequence"},
    {"route": "page/where-the-critic-learned-this", "type": "page", "passageId": "critic-origin", "cardId": null, "name": "Where the voice came from"},
    {"route": "page/self-talk", "type": "page", "passageId": "self-talk", "cardId": null, "name": "Managing self-talk"},
    {"route": "page/thinking-patterns", "type": "page", "passageId": "distortions", "cardId": null, "name": "Recognising thinking patterns"},
    {"route": "page/wise-mind", "type": "page", "passageId": "wise-mind", "cardId": null, "name": "Accessing Wise Mind"},
    {"route": "page/values", "type": "page", "passageId": "values", "cardId": null, "name": "Connecting with values"},
    {"route": "page/inner-voices", "type": "page", "passageId": "inner-voices", "cardId": null, "name": "Understanding inner voices"},
    {"route": "tool/sort-whats-yours-to-carry", "type": "tool", "passageId": "control-check-guided", "cardId": null, "name": "Control sort guided sequence"},
    {"route": "page/control-check", "type": "page", "passageId": "control-check", "cardId": null, "name": "Sorting what you can control"},
    {"route": "page/identity", "type": "page", "passageId": "identity", "cardId": null, "name": "Identity and growth"},
    {"route": "page/wider-context", "type": "page", "passageId": "systemic", "cardId": null, "name": "Wider context"},
    {"route": "tool/underneath-overwhelm", "type": "tool", "passageId": "deeper-overwhelmed", "cardId": null, "name": "Deeper reflection on overwhelm"},
    {"route": "tool/what-emotions-say", "type": "tool", "passageId": "deeper-emotions", "cardId": null, "name": "Deeper work with emotions"},
    {"route": "tool/decode-thinking-pattern", "type": "tool", "passageId": "deeper-distortions", "cardId": null, "name": "Decoding a thought pattern"},
    {"route": "tool/am-i-living-this", "type": "tool", "passageId": "deeper-values", "cardId": null, "name": "Living your values"},
    {"route": "tool/know-this-voice", "type": "tool", "passageId": "deeper-inner-voices", "cardId": null, "name": "Knowing your inner voices"},
    {"route": "tool/explore-versions-of-you", "type": "tool", "passageId": "deeper-identity", "cardId": null, "name": "Exploring versions of yourself"},
    {"route": "tool/name-where-it-came-from", "type": "tool", "passageId": "deeper-systemic", "cardId": null, "name": "Naming systemic sources"},
    {"route": "tool/message-in-a-bottle", "type": "tool", "passageId": "message-bottle", "cardId": null, "name": "A note to future you"},
    {"route": "tool/urge-surfing", "type": "tool", "passageId": "urge-surfing", "cardId": null, "name": "Urge surfing sequence"},
    {"route": "page/urges", "type": "page", "passageId": "urges", "cardId": null, "name": "I feel pulled toward something"},
    {"route": "page/my-toolbox", "type": "page", "passageId": "my-toolbox", "cardId": null, "name": "My Anchors"},
    {"route": "page/check-in-history", "type": "page", "passageId": "check-in-archive", "cardId": null, "name": "Earlier moments"},
    {"route": "page/tool-library", "type": "page", "passageId": "tools-index", "cardId": null, "name": "Tool Library"},
    {"route": "page/settle-before-surfing", "type": "page", "passageId": "urges-settle", "cardId": null, "name": "Slow down before urge surfing"},
    {"route": "tool/riding-out-a-strong-urge", "type": "tool", "passageId": "urge-check", "cardId": null, "name": "Before urge surfing"},
    {"route": "page/make-it-safer-first", "type": "page", "passageId": "urge-safer-first", "cardId": null, "name": "Make it safer first"},
    {"route": "page/how-this-works", "type": "page", "passageId": "about", "cardId": null, "name": "About Maps and Mirrors"},
    {"route": "tool/5-4-3-2-1-grounding", "type": "tool", "passageId": "overwhelmed", "cardId": "card-overwhelmed-5-4-3-2-1-grounding", "name": "5-4-3-2-1 Grounding"},
    {"route": "tool/paced-breathing", "type": "tool", "passageId": "overwhelmed", "cardId": "card-overwhelmed-paced-breathing", "name": "Paced Breathing"},
    {"route": "tool/6-10-rule", "type": "tool", "passageId": "overwhelmed", "cardId": "card-overwhelmed-the-610-rule", "name": "The 6/10 Rule"},
    {"route": "tool/physiological-sigh", "type": "tool", "passageId": "body", "cardId": "card-body-physiological-sigh", "name": "Physiological Sigh"},
    {"route": "tool/box-breathing", "type": "tool", "passageId": "body", "cardId": "card-body-box-breathing", "name": "Box Breathing"},
    {"route": "tool/temperature-shift", "type": "tool", "passageId": "body", "cardId": "card-body-temperature-shift", "name": "Temperature Shift"},
    {"route": "tool/feet-on-the-floor", "type": "tool", "passageId": "body", "cardId": "card-body-feet-on-the-floor", "name": "Feet on the Floor"},
    {"route": "tool/paired-muscle-relaxation", "type": "tool", "passageId": "body", "cardId": "card-body-paired-muscle-relaxation", "name": "Paired Muscle Relaxation"},
    {"route": "tool/buy-yourself-10-minutes", "type": "tool", "passageId": "urges", "cardId": "card-urges-buy-yourself-10-minutes", "name": "Buy Yourself 10 Minutes"},
    {"route": "tool/check-the-basics-first", "type": "tool", "passageId": "urges", "cardId": "card-urges-check-the-basics-first", "name": "Check the Basics First"},
    {"route": "tool/ride-it-out", "type": "tool", "passageId": "urges", "cardId": "card-urges-ride-it-out", "name": "Ride It Out"},
    {"route": "tool/name-it-to-tame-it", "type": "tool", "passageId": "emotions", "cardId": "card-emotions-name-it-to-tame-it", "name": "Name It to Tame It"},
    {"route": "tool/emotions-come-in-waves", "type": "tool", "passageId": "emotions", "cardId": "card-emotions-emotions-come-in-waves", "name": "Emotions Come in Waves"},
    {"route": "tool/guilt-vs-shame", "type": "tool", "passageId": "emotions", "cardId": "card-emotions-guilt-vs-shame-an-important-difference", "name": "Guilt vs Shame"},
    {"route": "tool/emotion-need-expression", "type": "tool", "passageId": "deeper-emotions", "cardId": "card-deeper-emotions-emotion-need-expression", "name": "Emotion → Need → Expression"},
    {"route": "leaves-on-a-stream.html", "type": "external", "passageId": null, "cardId": null, "name": "Leaves on a Stream"},
    {"route": "tool/worry-postponement", "type": "tool", "passageId": "thought-spiral", "cardId": "card-thought-spiral-worry-postponement", "name": "Worry Postponement"},
    {"route": "tool/im-having-the-thought-that", "type": "tool", "passageId": "self-talk", "cardId": "card-self-talk-im-having-the-thought-that", "name": "I'm Having the Thought That…"},
    {"route": "tool/friend-test", "type": "tool", "passageId": "self-talk", "cardId": "card-self-talk-the-friend-test", "name": "The Friend Test"},
    {"route": "tool/thought-diffusion", "type": "tool", "passageId": "self-talk", "cardId": "card-self-talk-thought-diffusion-lighten-the-grip", "name": "Thought Diffusion"},
    {"route": "tool/11-thinking-patterns", "type": "tool", "passageId": "distortions", "cardId": "card-distortions-11-patterns-worth-knowing", "name": "11 Thinking Patterns"},
    {"route": "tool/thought-record", "type": "tool", "passageId": "distortions", "cardId": "card-distortions-thought-record-4-steps", "name": "Thought Record"},
    {"route": "tool/one-small-thing", "type": "tool", "passageId": "stuck", "cardId": "card-stuck-one-small-thing", "name": "One Small Thing"},
    {"route": "tool/if-then-plan", "type": "tool", "passageId": "stuck", "cardId": "card-stuck-ifthen-plan", "name": "If/Then Plan"},
    {"route": "tool/reach-out-one-person", "type": "tool", "passageId": "alone", "cardId": "card-alone-one-reach-right-now", "name": "Reach Out — One Person"},
    {"route": "tool/hyperindependence", "type": "tool", "passageId": "alone", "cardId": "card-alone-hyperindependence", "name": "Hyperindependence in Recovery"},
    {"route": "tool/no-one-to-call", "type": "tool", "passageId": "alone", "cardId": "card-alone-if-you-have-no-one-to-call", "name": "If You Have No One to Call"},
    {"route": "tool/narrator-swap", "type": "tool", "passageId": "inner-voices", "cardId": "card-inner-voices-narrator-swap", "name": "Narrator Swap"},
    {"route": "tool/survival-and-chosen-identities", "type": "tool", "passageId": "identity", "cardId": "card-identity-survival-identities-vs-chosen-identities", "name": "Survival vs Chosen Identities"},
    {"route": "tool/reconstruction-prompts", "type": "tool", "passageId": "identity", "cardId": "card-identity-reconstruction-prompts", "name": "Reconstruction Prompts"},
    {"route": "tool/dearman", "type": "tool", "passageId": "interpersonal", "cardId": "card-interpersonal-dearman-ask-for-what-you-need-or-say-no", "name": "DEARMAN"},
    {"route": "tool/give", "type": "tool", "passageId": "interpersonal", "cardId": "card-interpersonal-give-stay-connected-while-you-say-it", "name": "GIVE", "expand": true},
    {"route": "tool/fast", "type": "tool", "passageId": "interpersonal", "cardId": "card-interpersonal-fast-keep-your-self-respect-intact", "name": "FAST", "expand": true},
    {"route": "tool/three-mind-states", "type": "tool", "passageId": "wise-mind", "cardId": "card-wise-mind-three-mind-states", "name": "Three Mind States"},
    {"route": "tool/wise-mind", "type": "tool", "passageId": "wise-mind", "cardId": "card-wise-mind-how-to-access-it-right-now", "name": "Access Wise Mind"},
    {"route": "tool/name-the-voice", "type": "tool", "passageId": "inner-voices", "cardId": "card-inner-voices-name-the-voice", "name": "Name the Voice"},
    {"route": "tool/question-the-voice", "type": "tool", "passageId": "inner-voices", "cardId": "card-inner-voices-question-it", "name": "Question the Voice"},
    {"route": "tool/what-are-values", "type": "tool", "passageId": "values", "cardId": "card-values-what-are-values", "name": "What Are Values?"},
    {"route": "tool/finding-your-values", "type": "tool", "passageId": "values", "cardId": "card-values-finding-yours-three-questions", "name": "Finding Your Values"},
    {"route": "tool/values-in-action", "type": "tool", "passageId": "values", "cardId": "card-values-values-in-action", "name": "Values in Action"},
    {"route": "tool/what-you-can-influence", "type": "tool", "passageId": "control-check", "cardId": "card-control-check-signs-you-can-influence-this", "name": "Signs You Can Influence This"},
    {"route": "tool/outside-your-control", "type": "tool", "passageId": "control-check", "cardId": "card-control-check-signs-this-is-outside-your-control", "name": "Signs This Is Outside Your Control"},
    {"route": "tool/whats-yours-to-carry", "type": "tool", "passageId": "deeper-overwhelmed", "cardId": "card-deeper-overwhelmed-step-2-whats-yours-to-carry", "name": "What's Yours to Carry?"},
    {"route": "tool/what-would-help-now", "type": "tool", "passageId": "deeper-overwhelmed", "cardId": "card-deeper-overwhelmed-step-3-what-would-help-most-right-now", "name": "What Would Help Most Right Now?"},
    {"route": "tool/emotion-myths", "type": "tool", "passageId": "deeper-emotions", "cardId": "card-deeper-emotions-rewrite-the-myth", "name": "Emotion Myths Rewritten"},
    {"route": "tool/what-is-this-pattern-doing", "type": "tool", "passageId": "deeper-distortions", "cardId": "card-deeper-distortions-talk-back-to-the-thought", "name": "What Is This Pattern Trying to Do?"},
    {"route": "tool/waiting-trap", "type": "tool", "passageId": "hypoarousal", "cardId": "card-hypoarousal-the-waiting-trap", "name": "The Waiting Trap"},
    {"route": "tool/one-small-move-right-now", "type": "tool", "passageId": "hypoarousal", "cardId": "card-hypoarousal-one-small-move-right-now", "name": "One Small Move Right Now"},
    {"route": "tool/say-what-you-need", "type": "tool", "passageId": "alone", "cardId": "card-alone-say-what-you-need", "name": "Say What You Need"},
    {"route": "tool/specific-loneliness", "type": "tool", "passageId": "alone", "cardId": "card-alone-the-specific-loneliness", "name": "The Specific Loneliness"},
    {"route": "tool/personal-vs-systemic", "type": "tool", "passageId": "systemic", "cardId": "card-systemic-sort-whats-personal-vs-systemic", "name": "Sort Personal vs Systemic"},
    {"route": "tool/check-in", "type": "tool", "passageId": "emotion-labeling", "cardId": null, "name": "Check in with yourself", "mode": "checkin"},
  ];
  var defaults = {
    "triage": "page/home",
    "one-beat": "tool/before-the-next-move",
    "crisis-now": "page/urgent-support",
    "hypoarousal": "page/low-flat-or-shut-down",
    "grief": "page/grief",
    "grief-death": "page/grief-and-death",
    "grief-death-died": "page/after-a-death",
    "grief-death-dying": "page/when-someone-is-dying",
    "grief-living": "page/living-loss",
    "grief-self-future": "page/grieving-self-and-future",
    "grief-multiple": "page/multiple-losses",
    "grief-support": "page/grief-support",
    "relationship": "tool/sort-through-a-relationship",
    "sort-through": "page/sort-through",
    "sort-through-reflect": "page/sort-through-reflection",
    "interpersonal": "page/boundaries-and-communication",
    "anticipatory": "page/prepare",
    "overwhelmed": "page/settle",
    "body": "page/body-tools",
    "running-on-empty": "tool/running-on-empty",
    "emotion-labeling": "tool/name-whats-here",
    "small-move": "tool/one-small-move",
    "emotions": "page/emotions",
    "stuck": "page/finding-direction",
    "alone": "page/bring-in-support",
    "support-plan-guided": "tool/support-plan",
    "thought-spiral": "page/thought-loops",
    "thought-spiral-guided": "tool/looping-thought",
    "self-talk-guided": "tool/reframe-inner-critic",
    "critic-origin": "page/where-the-critic-learned-this",
    "self-talk": "page/self-talk",
    "distortions": "page/thinking-patterns",
    "wise-mind": "page/wise-mind",
    "values": "page/values",
    "inner-voices": "page/inner-voices",
    "control-check-guided": "tool/sort-whats-yours-to-carry",
    "control-check": "page/control-check",
    "identity": "page/identity",
    "systemic": "page/wider-context",
    "deeper-overwhelmed": "tool/underneath-overwhelm",
    "deeper-emotions": "tool/what-emotions-say",
    "deeper-distortions": "tool/decode-thinking-pattern",
    "deeper-values": "tool/am-i-living-this",
    "deeper-inner-voices": "tool/know-this-voice",
    "deeper-identity": "tool/explore-versions-of-you",
    "deeper-systemic": "tool/name-where-it-came-from",
    "message-bottle": "tool/message-in-a-bottle",
    "urge-surfing": "tool/urge-surfing",
    "urges": "page/urges",
    "my-toolbox": "page/my-toolbox",
    "check-in-archive": "page/check-in-history",
    "tools-index": "page/tool-library",
    "urges-settle": "page/settle-before-surfing",
    "urge-check": "tool/riding-out-a-strong-urge",
    "urge-safer-first": "page/make-it-safer-first",
    "about": "page/how-this-works"
};
  var byKey = Object.create(null), byCard = Object.create(null);
  routes.forEach(function (route) {
    Object.freeze(route);
    byKey[route.route] = route;
    if (route.cardId) byCard[route.passageId + '/' + route.cardId] = route;
  });
  function parse(hash) {
    var explicit = !!hash && hash !== '#' && hash !== '#main-content';
    var key = (hash || '').slice(1);
    // Deliberately no DOM-ID fallback or free-form parameters.
    var route = /^((tool|page)\/[a-z0-9]+(?:-[a-z0-9]+)*)$/.test(key) && byKey[key];
    return { explicit: explicit, valid: !!route, route: route || byKey['page/home'] };
  }
  global.MMRoutes = Object.freeze({
    routes: Object.freeze(routes), defaults: Object.freeze(defaults),
    byKey: Object.freeze(byKey), parse: parse,
    forTarget: function (passageId, cardId) {
      return (cardId && byCard[passageId + '/' + cardId]) || byKey[defaults[passageId]] || byKey['page/home'];
    }
  });
  // Navigation-related deferred work participates in the current entry lifecycle.
  global.mmEntryLater = function (callback, delay) {
    return global.MMNavigation ? global.MMNavigation.later(callback, delay) : setTimeout(callback, delay);
  };
})(window);
